export interface Poem {
  id: string;
  title: string;
  author: string;
  dynasty: string;
  content: string[];
  tags: string[];
}

export const poems: Poem[] = [
  {
    id: "jing-ye-si",
    title: "静夜思",
    author: "李白",
    dynasty: "唐",
    content: ["床前明月光，", "疑是地上霜。", "举头望明月，", "低头思故乡。"],
    tags: ["思乡", "月亮"],
  },
  {
    id: "chun-xiao",
    title: "春晓",
    author: "孟浩然",
    dynasty: "唐",
    content: ["春眠不觉晓，", "处处闻啼鸟。", "夜来风雨声，", "花落知多少。"],
    tags: ["春天", "田园"],
  },
  {
    id: "deng-guan-que-lou",
    title: "登鹳雀楼",
    author: "王之涣",
    dynasty: "唐",
    content: ["白日依山尽，", "黄河入海流。", "欲穷千里目，", "更上一层楼。"],
    tags: ["哲理", "山水"],
  },
  {
    id: "xiang-si",
    title: "相思",
    author: "王维",
    dynasty: "唐",
    content: ["红豆生南国，", "春来发几枝。", "愿君多采撷，", "此物最相思。"],
    tags: ["咏物", "思念"],
  },
  {
    id: "jiang-xue",
    title: "江雪",
    author: "柳宗元",
    dynasty: "唐",
    content: ["千山鸟飞绝，", "万径人踪灭。", "孤舟蓑笠翁，", "独钓寒江雪。"],
    tags: ["冬天", "山水"],
  },
  {
    id: "you-zi-yin",
    title: "游子吟",
    author: "孟郊",
    dynasty: "唐",
    content: [
      "慈母手中线，",
      "游子身上衣。",
      "临行密密缝，",
      "意恐迟迟归。",
      "谁言寸草心，",
      "报得三春晖。",
    ],
    tags: ["亲情"],
  },
  {
    id: "wang-lu-shan-pu-bu",
    title: "望庐山瀑布",
    author: "李白",
    dynasty: "唐",
    content: [
      "日照香炉生紫烟，",
      "遥看瀑布挂前川。",
      "飞流直下三千尺，",
      "疑是银河落九天。",
    ],
    tags: ["山水"],
  },
  {
    id: "jue-ju",
    title: "绝句",
    author: "杜甫",
    dynasty: "唐",
    content: [
      "两个黄鹂鸣翠柳，",
      "一行白鹭上青天。",
      "窗含西岭千秋雪，",
      "门泊东吴万里船。",
    ],
    tags: ["春天", "山水"],
  },
  {
    id: "feng-qiao-ye-bo",
    title: "枫桥夜泊",
    author: "张继",
    dynasty: "唐",
    content: [
      "月落乌啼霜满天，",
      "江枫渔火对愁眠。",
      "姑苏城外寒山寺，",
      "夜半钟声到客船。",
    ],
    tags: ["秋天", "羁旅"],
  },
  {
    id: "deng-le-you-yuan",
    title: "登乐游原",
    author: "李商隐",
    dynasty: "唐",
    content: ["向晚意不适，", "驱车登古原。", "夕阳无限好，", "只是近黄昏。"],
    tags: ["哲理", "人生"],
  },
  {
    id: "ru-meng-ling",
    title: "如梦令·常记溪亭日暮",
    author: "李清照",
    dynasty: "宋",
    content: [
      "常记溪亭日暮，沉醉不知归路。",
      "兴尽晚回舟，误入藕花深处。",
      "争渡，争渡，惊起一滩鸥鹭。",
    ],
    tags: ["夏天", "生活"],
  },
  {
    id: "ti-xi-lin-bi",
    title: "题西林壁",
    author: "苏轼",
    dynasty: "宋",
    content: [
      "横看成岭侧成峰，",
      "远近高低各不同。",
      "不识庐山真面目，",
      "只缘身在此山中。",
    ],
    tags: ["哲理", "山水"],
  },
  {
    id: "shi-er",
    title: "示儿",
    author: "陆游",
    dynasty: "宋",
    content: [
      "死去元知万事空，",
      "但悲不见九州同。",
      "王师北定中原日，",
      "家祭无忘告乃翁。",
    ],
    tags: ["爱国"],
  },
  {
    id: "chun-ri",
    title: "春日",
    author: "朱熹",
    dynasty: "宋",
    content: [
      "胜日寻芳泗水滨，",
      "无边光景一时新。",
      "等闲识得东风面，",
      "万紫千红总是春。",
    ],
    tags: ["春天", "哲理"],
  },
  {
    id: "tian-jing-sha-qiu-si",
    title: "天净沙·秋思",
    author: "马致远",
    dynasty: "元",
    content: [
      "枯藤老树昏鸦，",
      "小桥流水人家，",
      "古道西风瘦马。",
      "夕阳西下，",
      "断肠人在天涯。",
    ],
    tags: ["秋天", "羁旅", "思乡"],
  },
  {
    id: "zhu-shi",
    title: "竹石",
    author: "郑燮",
    dynasty: "清",
    content: [
      "咬定青山不放松，",
      "立根原在破岩中。",
      "千磨万击还坚劲，",
      "任尔东西南北风。",
    ],
    tags: ["咏物", "哲理"],
  },
  {
    id: "ji-hai-za-shi",
    title: "己亥杂诗·其五",
    author: "龚自珍",
    dynasty: "清",
    content: [
      "浩荡离愁白日斜，",
      "吟鞭东指即天涯。",
      "落红不是无情物，",
      "化作春泥更护花。",
    ],
    tags: ["爱国", "人生"],
  },
];
